### ISSUE TITLE
Cliquer sur une note

### ISSUE THREAD

**Issue by Amleth** [sherlock-iremus/sherlock-tonalities#104]
Quand on clique sur une note, on aimerait que le navigateur d'individus analytiques scrolle vers la première annotation contenant cette note.

**Comment by Amleth** [comment]
https://codingbeautydev.com/blog/react-scroll-to-element/

**Comment by guillotel-nothmann** [comment]
Je confirme que ceci est très gênant. L'interface gagnerait nettement en ergonomie si cette fonctionnalité était implémentée. 
Afin d'éviter les conflit si plusieurs annotations portent sur la même note, par convention, la dernière annotation créée pourrait être retenue.
