### ISSUE TITLE
Add a playback button

### ISSUE THREAD

**Issue by guillotel-nothmann** [sherlock-iremus/sherlock-tonalities#115]
It would be great to be able to play the score. Verovio has a feature for this. Would it be possible to implement it and add a button?

**Comment by felix-commits** [comment]
En attente de validation
<img width="1449" alt="Capture d’écran 2024-05-22 à 14 10 12" src="https://github.com/sherlock-iremus/sherlock-tonalities/assets/70573684/c4855198-9ae1-4581-8d5f-52db79571574">

**Comment by felix-commits** [comment]
à tester sur https://sherlock-iremus.github.io/sherlock-tonalities/

**Comment by guillotel-nothmann** [comment]
Il serait très bien que les notes jouées soient mises en surbrillance comme dans NEUMA.
