### ISSUE TITLE
Select a licence when creating a project

### ISSUE THREAD

**Issue by guillotel-nothmann** [sherlock-iremus/sherlock-tonalities#117]
It would be great if we could select a licence (i.e. cc licence) when creating a project.

**Comment by guillotel-nothmann** [comment]
Je ne suis pas vraiment d’accord avec la licence Etalab et, comme nous l’avions convenu, il faudra que nous menions une discussion avec nos référents à ce sujet. 

c.

**Comment by Amleth** [comment]
Pourrais-tu nous expliquer concrètement te réticences sur cette licence ? Le côté français ? (son usage est encouragé par nos tutelles). Si on trouve le plus proche dans l'esprit mais à un niveau international, ce serait acceptable pour toi ?
