### ISSUE TITLE
La liste des annotations revient systématiquement à la page 1

### ISSUE THREAD

**Issue by guillotel-nothmann** [sherlock-iremus/sherlock-tonalities#132]
Après la sélection d’une annotation, une fois avoir cliqué sur X, la liste des annotations revient systématiquement à la page 1. C’est très gênant : on ne retrouve plus l’annotation en question sur plusieurs pages.

**Comment by felix-commits** [comment]
je ne parviens pas à reproduire le problème, lorsqu'une annotation est déselectionnée, la page doit être inchagée. peux-tu détailler ?

**Comment by guillotel-nothmann** [comment]
Désolé de ne pas avoir été assez clair. Cette vidéo illustre le problème: https://drive.google.com/file/d/1uj53e6WF52KtL-RB4NG5sDXt31zPwZ0W/view?usp=sharing

**Comment by felix-commits** [comment]
D'accord je comprends maintenant. C'est en lien avec le ticket #104 proposé par @Amleth, je vais reprioriser son developpement

**Comment by guillotel-nothmann** [comment]
Filtrer les annotations en conséquence: ne laisser visible que l'annotation sélectionnée.
