### ISSUE TITLE
Button "Report a bug"

### ISSUE THREAD

**Issue by margur78** [sherlock-iremus/sherlock-tonalities#135]
A button "Report a bug", linked to GitHub repository, is already present in the welcome page. Please an identical button should be added in each page, once you choice the score.

v

**Comment by guillotel-nothmann** [comment]
Je crois qu'il y a un problème de compréhension ici. Marco veut dire qu'il faudrait un bouton directement dans l'interface d'annotation. 
<img width="552" alt="Capture d’écran 2024-01-19 à 08 47 59" src="https://github.com/sherlock-iremus/sherlock-tonalities/assets/16302877/6b0f7ac8-38e0-4760-955f-288af19063e6">

**Comment by guillotel-nothmann** [comment]
Excellent ! Merci, Félix !
