### ISSUE TITLE
Effacer les projets entiers

### ISSUE THREAD

**Issue by guillotel-nothmann** [sherlock-iremus/sherlock-tonalities#140]
À ce stade, il serait très utile de pouvoir effacer des projets analytiques entiers. Il existe par exemple ici [1] un projet "Cadences" créé par "N".  Est-il possible d'effacer ce projet (ou au moins toutes les annotations indviduelles – je ne sais pas qui a créé ce projet). 

https://data-iremus.huma-num.fr/tonalities/project/5f58efc2-3091-4b53-a235-0afc02b0ee7e/score/28fae3a2-3510-4ea7-b783-8f2f7e5be86d

**Comment by felix-commits** [comment]
[ticket de résolution](https://github.com/sherlock-iremus/sherlock-service/issues/15) côté serveur
