### ISSUE TITLE
Selection d'une plage sur plusieurs portées

### ISSUE THREAD

**Issue by guillotel-nothmann** [sherlock-iremus/sherlock-tonalities#146]
Le problème se rapporte à #124  qui a été fermé: 

"At the current stage it is possible to select a) individual elements, b) note ranges on one single staff and c)verticalities. It would be very helpful if additionaly whole sections could be selected: shift + first note upper staff – shift + last note lower staff (or the other way around)."

Au stade actuel, il n'est toujours pas possible de sélectionner une plage de notes / silences sur plusieurs portées: seule la sélection d'une plage sur une seule portée est possible.

**Comment by margur78** [comment]
Petit bug (voir capture d'écran en PJ) : si on sélectionne un système en bas du premier système sélectionné, la plage sélectionnée est limitée à la section verticale réalisée...
<img width="1792" alt="Capture d’écran 2024-01-31 à 14 37 41" src="https://github.com/sherlock-iremus/sherlock-tonalities/assets/81967190/f8de0f15-354a-4326-b946-4e6c60c99145">

**Comment by guillotel-nothmann** [comment]
Pour une raison que je ne parviens pas complètement à reconstituer, certaines notes ne sont pas incluses dans la sélection des plages (voir plus bas dans l'exemple).
Par ailleurs, il faudrait aussi que la sélectionne tienne compte de tous les silences... 
 Peut-être pourras-tu jeter un oeil ? 

<img width="768" alt="Capture d’écran 2024-01-31 à 12 10 06" src="https://github.com/sherlock-iremus/sherlock-tonalities/assets/16302877/c9851e04-3074-40d2-9282-e6b0164856a8">
