### ISSUE TITLE
La déconnexion n'est pas signalée. 

### ISSUE THREAD

**Issue by guillotel-nothmann** [sherlock-iremus/sherlock-tonalities#149]
Les utilisateurs ne savent pas quand l'interface est déconnectée. Du coup ils tentent de réaliser des actions qui n'ont pas d'effet et pensent qu'il s'agit d'une problème technique. Est-il possible de changer d'écran une fois que l'interface est déconnectée suite à une activité prolongée? Ceci concerne l'écran de sélection ET l'écran d'annotaiton.

**Comment by guillotel-nothmann** [comment]
Il reste toujouts un problème ici: la déconnexion ne se fait pas. Elle est signalée à présent mais l'identifiant (par exemple "C") reste toujouts visible, même après la déconnexion, ce qui ne devrait pas être le cas.

**Comment by felix-commits** [comment]
> Il reste toujouts un problème ici: la déconnexion ne se fait pas. Elle est signalée à présent mais l'identifiant (par exemple "C") reste toujouts visible, même après la déconnexion, ce qui ne devrait pas être le cas.

En effet, le problème persiste sur certains navigateurs
