### ISSUE TITLE
Impossible d'ouvrir les fichiers du corpus BACH

### ISSUE THREAD

**Issue by guillotel-nothmann** [sherlock-iremus/sherlock-tonalities#156]
Lors de l'ouverture des fichiers, le problème suivant est signalé:

<img width="631" alt="Capture d’écran 2024-02-19 à 11 56 25" src="https://github.com/sherlock-iremus/sherlock-tonalities/assets/16302877/7d281ed5-7f25-429a-b5a0-9214b79200d1">

**Comment by felix-commits** [comment]
Peux tu transmettre l'url de projet qui renvoie cette erreur ?
