### ISSUE TITLE
Partition introuvable

### ISSUE THREAD

**Issue by guillotel-nothmann** [sherlock-iremus/sherlock-tonalities#169]
Je ne trouve pas cette partition sur l'interface:

https://raw.githubusercontent.com/polifonia-project/tonalities_pilot/main/scores/Zarlino/Zarlino_Miserere_mei

**Comment by Amleth** [comment]
Le fichier n'est pas correctement nommé : il manque l'extension .mei.

**Comment by guillotel-nothmann** [comment]
Merci, je n'avais pas vu sur le coup...
