### ISSUE TITLE
Il manque une autre partition

### ISSUE THREAD

**Issue by guillotel-nothmann** [sherlock-iremus/sherlock-tonalities#170]
Je ne parviens pas à identifier cette partition non plus:

https://raw.githubusercontent.com/polifonia-project/tonalities_pilot/main/scores/Josquin/Josquin_Sacred_Music/Josquin_Preter_rerum_seriem.mei

**Comment by Amleth** [comment]
Ce fichier n'existe pas dans Github.

cf : https://github.com/polifonia-project/tonalities_pilot/tree/main/scores/Josquin/Josquin_Sacred_Music

**Comment by guillotel-nothmann** [comment]
Cher Marco,
Le fichier suivant a disparu de Github. Pourrais-tu le remettre s’il te plaît ?
https://raw.githubusercontent.com/polifonia-project/tonalities_pilot/main/scores/Josquin/Josquin_Sacred_Music/Josquin_Preter_rerum_seriem.mei


Bien amicalement,
Christophe
---
Christophe Guillotel-Nothmann
Chargé de Recherche CNRS
IReMus UMR 8223
CNRS, Sorbonne Université, BnF, Culture
Quai François Mauriac
75706 PARIS Cedex 13


Le 29 mars 2024 à 11:33, Thomas ⬡ Bottini ***@***.******@***.***>> a écrit :



Ce fichier n'existe pas dans Github.

cf : https://github.com/polifonia-project/tonalities_pilot/tree/main/scores/Josquin/Josquin_Sacred_Music

**Comment by guillotel-nothmann** [comment]
Le fichier était mal nommé, à nouveau. Il est ici:

https://raw.githubusercontent.com/polifonia-project/tonalities_pilot/main/scores/Josquin/Josquin_Sacred_Music/Josquin_Preter_rerum.mei
