### ISSUE TITLE
Agrandir la fenêtre "commentaire"

### ISSUE THREAD

**Issue by guillotel-nothmann** [sherlock-iremus/sherlock-tonalities#174]
C'est dans le titre: la fenêtre qui permet de saisir les commentaires est trop petite. Il faudrait l'agrandir pour laisser apparaître 3-4 lignes. Est-il possible que la taille de la fenêtre s'adapte au contenu en cours d'édition, comme dans google docs ?

**Comment by guillotel-nothmann** [comment]
A priori, la fenêtre commentaire n'est pas plus grand à présent,,,

**Comment by felix-commits** [comment]
je viens de mettre en production, la zone de texte s'agrandit si on ajoute un retour à la ligne

**Comment by guillotel-nothmann** [comment]
Parfait. Ça marche 👌
