### ISSUE TITLE
Afficher systématiquement les dates des annotations + commentaires.

### ISSUE THREAD

**Issue by guillotel-nothmann** [sherlock-iremus/sherlock-tonalities#175]
Il serait bien que les dates des annotations + commentaires soient toutes affichées par défaut. Comme ceci, par exemple:

<img width="276" alt="Capture d’écran 2024-04-11 à 14 33 51" src="https://github.com/sherlock-iremus/sherlock-tonalities/assets/16302877/1ab59bb8-8c83-4280-891d-c7179433ede2">

Au stade actuel, l'info n'est accessible que lorsque l'on accède au niveau du concept en passant la souris dessus. C'est beaucoup trop fastidieux.

**Comment by guillotel-nothmann** [comment]
Les dates ne s'affichent toujours pas, sauf erreur,

**Comment by guillotel-nothmann** [comment]
À ce stade on a un décompte « created 2 months ago with 5 items ». Serait-il possible d’avoir la date exacte de création : 24/03/2024 12:23 ?
Ce serait plus lisible. (Le nombre d’items ajoutés par compte n’est pas si important, je crois).

**Comment by felix-commits** [comment]
interface mise à jour avec le nouveau format `20/12/2012, 03:00`

**Comment by guillotel-nothmann** [comment]
Excellent !
