### ISSUE TITLE
liste des individuals - l'empêcher de se réinitialiser

### ISSUE THREAD

**Issue by Adam-Filaber** [sherlock-iremus/sherlock-tonalities#190]
Quand on sort d’un « individual », la liste des « individuals » se réinitialise. Cela fait que c’est difficile de se repérer, surtout quand il y a une longue liste et l’individu qu’on vient d’annoter se trouve quelque part au milieu.

**Comment by guillotel-nothmann** [comment]
Cher Félix, 
Merci pour tout ton travail au cours des dernières heures. Suite à la mise en production, j’observe toutefois des erreurs récurrentes a) lors de la lecture des fichiers et b) lors de la sélection d’annotations. 
a) En rechargeant la page, le problème peut parfois être contourné b) il n’y pas possible de sélectionner les annotations. L’erreur suivante s’affiche: 

￼

Pourrais-tu regarder. 

Bien amicalement, 
Christophe
