### ISSUE TITLE
Ergonomics: No validation of each action

### ISSUE THREAD

**Issue by guillotel-nothmann** [sherlock-iremus/sherlock-tonalities#72]
No validation of each action. This takes too much time and does not make sense methodologically. Add instead a global validation option. This global validation would be made once (for example at the end of a working session, or when an analytical task is completed, all roots analyzed, all dissonances analysed, cadences corrected). This would also have the advantage of making available different published versions – like different pushes on GitHub - at different timepoints that would correspond to different analyses.

**Comment by margur78** [comment]
Attention ! Le bouton "Validation" dois être remplacé par "Publish" (voir ticket "Terminology: Validate")
